using System.IO;
using ShellScript.Core;
using ShellScript.Core.Language.Compiler.Transpiling;

namespace ShellScript.Windows.Batch.PlatformTranspiler
{
    public class BatchPlatformMetaInfoTranspiler : IPlatformMetaInfoTranspiler
    {
        public void WritePrologue(Context context, TextWriter writer)
        {
            writer.WriteLine("@echo off");
            writer.WriteLine("setlocal EnableExtensions");

            if (context.Flags.WriteShellScriptVersion)
            {
                writer.Write("REM ShellScript v");
                writer.Write(ApplicationContext.Version);
                writer.Write(" - [");
                writer.Write(ApplicationContext.Url);
                writer.WriteLine("]");
            }
            
//            if (context.WriteAutoGeneratedCodeNotice)
//            {
//                writer.Write("#NOTICE: This file generated automatically with a transpiler tool, ");
//                writer.Write("use of this code requires you to accept the terms available at [");
//                writer.Write(ApplicationContext.Url);
//                writer.WriteLine("].");
//            }

            if (!string.IsNullOrWhiteSpace(context.Flags.Author))
            {
                writer.Write("Author: ");
                writer.WriteLine(context.Flags.Author);
            }

            if (!string.IsNullOrWhiteSpace(context.Flags.ContactInfo))
            {
                writer.Write("ContactInfo: ");
                writer.WriteLine(context.Flags.ContactInfo);
            }

            if (!string.IsNullOrWhiteSpace(context.Flags.WikiUrl))
            {
                writer.Write("Wiki: ");
                writer.WriteLine(context.Flags.WikiUrl);
            }

            if (context.Flags.UseSegments)
            {
                BatchTranspilerHelpers.WriteSeparator(writer);
            }
        }

        public void WriteEpilogue(Context context, TextWriter writer)
        {
        }

        
        public void WriteComment(Context context, TextWriter writer, string comment)
        {
            BatchTranspilerHelpers.WriteComment(writer, comment);
        }

        public void WriteSeparator(Context context, TextWriter writer)
        {
            BatchTranspilerHelpers.WriteSeparator(writer);
        }
    }
}